print logprep version via cli
fkie-cad/Logprep pull request #136
Opened 2022-07-01 12:12 UTC by dtrai2

Adds the changes to the documentation

2022-07-06 08:27 UTC, urdit52 requested changes
I have requested and suggested 2 minor things.

2022-07-06 08:27 UTC, urdit52 commented on CHANGELOG.md
> +With that it has to be used when passing a configuration to logprep
This is misleading. How about:
```suggestion
This makes it necessary to explicitly use the argument --config when a config is to be passed to logprep.
```

2022-07-06 08:27 UTC, urdit52 commented on tests/unit/test_run_logprep.py
> +    def test_version_arg_prints_logprep(self, capsys):
this also tests for the case that no config version is specified, which should be reflected in the test name.

2022-07-06 13:01 UTC, urdit52 approved these changes
thanks for fixing this.

2022-07-07 10:13 UTC, ppcad commented
Useful changes! I also like that you can version the config now.

If you change the config parameter to be like below, then you could  still use _--version_ without having to specify a config and it would not be e breaking change.

```
argument_parser.add_argument(
        "config", nargs='?',
        help=f"Path to configuration file, if not given then "
        f"the default path '{DEFAULT_LOCATION_CONFIG}' is used",
        default=DEFAULT_LOCATION_CONFIG,
    )
```

You would also have to change some of the feedback messages that were written with _--config_ in mind.

What do you think? Am I missing something? I would like to avoid breaking changes if possible.

2022-07-08 05:00 UTC, ppcad approved these changes
Thanks!

2022-07-08 05:00 UTC, merged