Add OpenSearch output connector
fkie-cad/Logprep pull request #174
Opened 2022-08-31 10:43 UTC by ppcad

2022-09-05 13:30 UTC, urdit52 commented on logprep/connector/opensearch/output.py
> +            except SerializationError as error:
These Errors are all untested as of yet.

2022-09-05 14:15 UTC, urdit52 requested changes
Thank you very much for submitting this.

Could we please increase the test coverage back up to 100%?

Also, the code is almost exactly the same as the ES connector. Should we maybe refactor this to avoid duplicated code?

2022-09-05 14:15 UTC, urdit52 commented on logprep/connector/opensearch/output.py
> +            except SerializationError as error:
These errors are untested.

2022-09-05 14:15 UTC, urdit52 commented on logprep/connector/opensearch/output.py
> +                self._input.batch_finished_callback()
this is untested.

2022-09-05 14:15 UTC, urdit52 commented on logprep/connector/opensearch/output.py
> +            self._processed_cnt = currently_processed_cnt
this is untested.

2022-09-05 14:15 UTC, urdit52 commented on logprep/connector/opensearch/output.py
> +        error_documents = []
188-197 are untested.

2022-09-05 14:15 UTC, urdit52 commented on logprep/connector/opensearch/output.py
> +        raise FatalOutputError(f"{error.args[1]} in document {error.args[0]}")
this is untested.

2022-09-07 05:15 UTC, ppcad commented on logprep/connector/opensearch/output.py
> +                self._input.batch_finished_callback()
I've added a test.

2022-09-07 05:15 UTC, ppcad commented on logprep/connector/opensearch/output.py
> +            self._processed_cnt = currently_processed_cnt
I've added a test.

2022-09-07 05:15 UTC, ppcad commented on logprep/connector/opensearch/output.py
> +        raise FatalOutputError(f"{error.args[1]} in document {error.args[0]}")
I've added a test.

2022-09-07 05:16 UTC, ppcad commented on logprep/connector/opensearch/output.py
> +        error_documents = []
I've added a test.

2022-09-07 05:19 UTC, ppcad commented on logprep/connector/opensearch/output.py
> +            except SerializationError as error:
I've added a test.

2022-09-07 13:51 UTC, urdit52 commented on logprep/connector/opensearch/output.py
> +            ssl_context.check_hostname = check_hostname
I added a test.

2022-09-07 13:54 UTC, urdit52 approved these changes

2022-09-07 13:55 UTC, merged