Delete flipping aggregation test
fkie-cad/Logprep pull request #222
Opened 2022-11-19 19:27 UTC by ekneg54

* if someone knows what it does or what we want to test, then provide comments.

2022-11-21 08:34 UTC, ppcad commented
This tests if the aggregator keeps aggregating in consecutive aggregations even if the aggregation threshold was not exceeded.

Example:
Aggragate after 3 logs within 0.25 seconds. The following should happen:

- First 0.25 sec period if #logs>3: Print the first 3 logs as seperate logs and then start aggregating the rest for this period.
  - A. Following 0.25 sec period if #logs>3: Don't print the first 3 logs despite the threshold being not yet exceeded, since the aggregations are consecutive. Aggregate everything for those periods.
  - B. Following 0.25 sec period if #logs<= 3: Print the first 3 logs normally. The next aggregation won't be consecutive, thus 3 logs will be printed again.

This means, the first 3 logs should not be printed for every consecutive aggregation period in which the threshold has been exceeded.

We should get something like this:
"Some log message"
"Some log message"
"Some log message"
"Some log message (6 in ~0.25 sek)"
"Some log message (4 in ~0.25 sek)"
"Some log message (5 in ~0.25 sek)"
(>0.25 sec passed)
"Some log message"
(>0.25 sec passed)
"Some log message"
"Some log message"
"Some log message"
"Some log message (5 in ~0.25 sek)"
"Some log message (7 in ~0.25 sek)"

This has to be testet somewhere.

2022-11-21 08:38 UTC, ekneg54 commented
ahh... ok... right... Thank you for the explanation...  I will do my best, to implement it in a testable way or rewrite a stable non flipping test for it.

2022-11-21 08:39 UTC, ppcad commented
> ahh... ok... right... Thank you for the explanation... I will do my best, to implement it in a testable way or rewrite a stable non flipping test for it.

Thank you, that would be great!

2022-11-23 12:57 UTC, ppcad requested changes

2022-11-23 12:57 UTC, ppcad commented on logprep/util/log_aggregator.py
> -    @staticmethod
Logprep will crash without "filter". It is required to perform the aggregation with the logger.
The remaining methods that you removed did not seem to be called anywhere.

2022-11-24 12:33 UTC, ppcad approved these changes
Thanks for the fix!

2022-11-24 12:33 UTC, merged