add list access to get_dotted_field_value
fkie-cad/Logprep pull request #299
Opened 2023-01-25 16:17 UTC by ekneg54

* this adds simple list access to `get_dotted_field_value` helper function
* slicing is not supportet yet

2023-01-25 16:23 UTC, ekneg54 commented
closes #298

2023-01-26 08:59 UTC, dtrai2 requested changes

2023-01-26 08:59 UTC, dtrai2 commented on logprep/util/helper.py
> +        return list.__getitem__(items, int(item))
looks good to me. I am not sure if there is a need for it, but it is fairly simple to extend this to get characters from a string with `str.__getitem__(items, int(item))`. As one single character might be uninteresting though you could also extend it with the slicing functionality. For that you "just" have to check if the `item` string has a `:` colon in it, split the string and pass it into the `slice(start, stop, step)` method.

2023-01-26 08:59 UTC, dtrai2 commented on logprep/util/helper.py
>          return None
Here you also have to check for the `IndexError` and write in the `test_helper.py` file a corresponding test. Just for the cases where someone tries to access an element, that is outside of the boundaries of the collection.

2023-01-26 14:25 UTC, dtrai2 approved these changes
I just added some documentation and more test cases, as well as the case for IndexErrors. On my side it can be merged now, but please take a look at my changes first before doing so.

2023-01-26 16:54 UTC, merged