add processor boilerplate generator helper
fkie-cad/Logprep pull request #302
Opened 2023-01-27 16:02 UTC by ekneg54

2023-01-30 08:44 UTC, dtrai2 requested changes
neat little generator :+1: Could you add it also to the changelog, please.

2023-01-30 08:44 UTC, dtrai2 commented on logprep/util/template_processor_test.py.j2
> +        assert event == expected, testcase
```suggestion
        assert event == expected, testcase

```

2023-01-30 08:44 UTC, dtrai2 commented on logprep/util/processor_generator.py
> +import sys
```suggestion
```

2023-01-30 17:41 UTC, ekneg54 commented on logprep/util/template_processor.py.j2
> +        ...
done

2023-01-30 17:44 UTC, ekneg54 commented on logprep/util/template_rule.py.j2
> +{{ processor.class_name}}
no... the other processorrules do not do this

2023-01-30 17:47 UTC, ekneg54 commented on doc/source/development/processor_how_to.rst
> +Getting started
done

2023-01-30 17:51 UTC, ekneg54 commented on logprep/util/template_processor_test.py.j2
> +        assert event == expected
done

2023-01-30 17:53 UTC, ekneg54 commented on logprep/util/processor_generator.py
> +    name: str = field(validator=validators.instance_of(str), converter=camel_to_snake)
later ? ;)

2023-01-30 18:03 UTC, ekneg54 commented on logprep/util/processor_generator.py
> +    name: str = field(validator=validators.instance_of(str), converter=camel_to_snake)
done

2023-01-31 08:10 UTC, dtrai2 approved these changes

2023-01-31 08:18 UTC, merged