Fix catched exception in tree parser that led to ignoring of rules
fkie-cad/Logprep pull request #343
Opened 2023-03-10 13:13 UTC by ppcad

Sometimes the tree parser tries to remove to many elements from the expression when parsing.
In that case it prints a warning and ignores that rule. However, if started with the auto-tester it doesn't even print a warning.
This can be reproduced by having a conjunction of at least four disjunctions.

This pull request prevents the crash that leads to the warning so that the rules won't be ignored.

2023-04-20 17:24 UTC, ekneg54 requested changes
could you please rewrite this parser? it is one of the worst readable code fragments in logprep and it would be a real improvement, if someone rewrites it so it is more readable.

2023-04-20 17:24 UTC, ekneg54 commented on logprep/framework/rule_tree/rule_parser.py
we should really rewrite this to make it readable for others. I have no clue, what is happening.

2023-04-21 05:28 UTC, ppcad commented on logprep/framework/rule_tree/rule_parser.py
This will be a bigger project, this pull request is just meant to fix the bug.

2023-04-21 05:42 UTC, ppcad commented on logprep/filter/expression/filter_expression.py
>          return ".".join([str(i) for i in key_list])
It's probably not needed then. It's not related to this pull-request and I would rather not change to many thing at once in the tree-parser in this pull-request.

2023-04-21 06:49 UTC, ekneg54 commented on logprep/framework/rule_tree/rule_parser.py
I added a story for that: #376

2023-04-21 06:50 UTC, ekneg54 approved these changes

2023-04-21 09:34 UTC, merged