remove logaggregator
fkie-cad/Logprep pull request #439
Opened 2023-09-07 09:27 UTC by ekneg54

In our work we noticed a big memory leak during debug mode. this should resolve it. 

@ppcad please confirm, that you do not need the log aggregation, because we do not need it either.

2023-09-07 11:23 UTC, ppcad commented
Thank you for finding this! I need to check if aggregation is still needed.

2023-09-08 06:32 UTC, ppcad commented
Log aggregation is still needed, so please don't remove it.
Fixing the leak will be the preferred solution if that is possible.

2023-09-08 19:01 UTC, ekneg54 commented
The other way to fix it is to only log generic lines to avoid that the dict is getting bigger and bigger. 
but what kind of "logger" would this be? 😄

2023-09-15 06:28 UTC, dtrai2 requested changes

2023-09-15 06:28 UTC, dtrai2 commented on logprep/run_logprep.py
> +}
you don't need this, as you can throw in the logel-level string from `log_config.get("level", ...)` directly into the `basicConfig(level=log_level, ...)` call.
```suggestion
```

2023-09-15 06:28 UTC, dtrai2 commented on logprep/run_logprep.py
> +        log_level = name_to_level.get(log_level_name)
as above
```suggestion
```

2023-09-15 06:28 UTC, dtrai2 commented on logprep/run_logprep.py
> +    NOTSET,
see below
```suggestion
```

2023-09-15 06:28 UTC, dtrai2 commented on logprep/run_logprep.py
> +        log_level_name = log_config.get("level", "INFO")
```suggestion
        log_level = log_config.get("level", "INFO")
```

2023-09-15 06:28 UTC, dtrai2 commented on logprep/run_logprep.py
> +        logger.info(f"Log level set to '{log_level_name}'")
```suggestion
        logger.info(f"Log level set to '{log_level}'")
```

2023-09-15 06:32 UTC, dtrai2 commented
ah, can you also please add a CHANGELOG.md entry.

2023-09-15 10:50 UTC, dtrai2 approved these changes

2023-09-15 11:20 UTC, merged