Revise Metrics
fkie-cad/Logprep pull request #460
Opened 2023-10-11 08:43 UTC by dtrai2

2023-11-08 14:33 UTC, ekneg54 approved these changes

2023-11-08 14:36 UTC, dtrai2 commented
hey @ppcad we have reached a point in the metric refactoring where we would like to have your feedback. Could you please check it out and see if it works as expected. You don't have to do an in-depth code review. I think just having a look at it and testing it out should suffice. Thanks.

2023-11-10 10:40 UTC, ppcad commented
Those changes are amazing! I have only one small remark: The pipeline times are never added to events, even if APPEND_TO_EVENT is set. Still having those times would be great if that's possible without a massive hassle.

2023-11-10 10:41 UTC, ppcad requested changes
Those changes are amazing! I have only one small remark: The pipeline times are never added to events, even if APPEND_TO_EVENT is set. Still having those times would be great if that's possible without a massive hassle. Otherwise I would approve it now. What do you say?

There is one more thing: The directory PROMETHEUS_MULTIPROC_DIR is now deleted after Logprep is shut down.
This means that that the directory needs to be re-created each time Logprep restarts. Is this the desired behaviour?

2023-11-10 11:59 UTC, ekneg54 commented
hello @ppcad ,

the PROMETHEUS_MULTIPROC_DIR should only be cleared. not deleted. but you have to provide it. 

in a kubernetes environment you could add a empty dir volume to the deployment and mount this. so the volume is there when logprep starts.

2023-11-10 12:02 UTC, ppcad commented
Okay, in that case it needs to be fixed.
Logprep deletes it instead of clearing it.
At the moment you have to re-create it every time you restart Logprep.

2023-11-14 09:30 UTC, dtrai2 commented
I checked out the pipeline processing times and how we could add them to the events. The problem is with the current implementation it is not possible as we are using two different decorators for this. If the events should be appended with the processing times we use one decorator for it and if we do not want to append the processing times we use a different decorator. Now the problem is that the decorators are applied on module load time. Meaning if we load a module before the configuration is parsed we might decorate a function with the wrong decorator. The processor python files are luckily loaded after the configuration was parsed, the pipeline though seems to be loaded before the configuration was parsed. So event if I extend the appending functionality the pipeline processing times still won't be appended as the configuration is set too late. I see now the following options:
1. We refactor some of the `run_logprep` implementation such that most modules are not imported at the top of the file, but rather after the configuration was parsed.
2. We do not use two separate decorators, but instead have one decorator with an if-statement inside, which would mean though that it will be evaluated on everything that tracks processing times. 
3. We do make it necessary that this is something that has to be configured via an environment variable. That way it would be independent of the load of `pipeline.yaml` config file. Or
4. We drop pipeline processing times and only append the processor/rule processing times in the events.

If we want to add this again I personally would pick option 3. It is not consistent with our current configuration pattern, but has the smallest impact on code changes. Considering that this might be dropped in the future I think it is a good enough solution. 

@ekneg54 @ppcad any thoughts on this?

2023-11-14 09:39 UTC, ppcad commented
I agree. If it has the least impact on the code, then I would pick option 3, since appending to events will be eventually completely removed.

2023-11-14 12:22 UTC, ekneg54 commented
option 3 please 👍

2023-11-14 14:55 UTC, ekneg54 approved these changes

2023-11-16 08:07 UTC, ekneg54 requested changes
plz add my changes in dashboards, cause it leads to not showing garbage collections

2023-11-16 08:07 UTC, ekneg54 commented on quickstart/exampledata/config/grafana/dashboards/logprep-dashboard.json
> +          "expr": "sum(increase(logprep_number_of_failed_events_total{container=~\".*logprep\"}[$__range]))",
```suggestion
          "expr": "sum(increase(logprep_number_of_failed_events_total[$__range]))",
```

2023-11-16 08:07 UTC, ekneg54 commented on quickstart/exampledata/config/grafana/dashboards/logprep-dashboard.json
> +          "expr": "sum(rate(python_gc_collections_total{container=~\".*logprep\"}[1m]))",
```suggestion
          "expr": "sum(rate(python_gc_collections_total[1m]))",
```

2023-11-16 08:07 UTC, ekneg54 commented on quickstart/exampledata/config/grafana/dashboards/logprep-dashboard.json
> +          "expr": "sum(rate(python_gc_objects_collected_total{container=~\".*logprep\"}[1m]))",
```suggestion
          "expr": "sum(rate(python_gc_objects_collected_total[1m]))",
```

2023-11-16 10:22 UTC, ekneg54 approved these changes

2023-11-17 06:24 UTC, ppcad requested changes
I marked two places where the environment variable was not replaced with the new name.
Other than that it works great and I will approve it as soon as this is changed.

2023-11-17 06:24 UTC, ppcad commented on tests/unit/metrics/test_metrics.py
> +        os.environ["APPEND_TO_EVENT"] = "1"
This needs to be `LOGPREP_APPEND_MEASUREMENT_TO_EVENT`

2023-11-17 06:24 UTC, ppcad commented on tests/unit/metrics/test_metrics.py
> +        del os.environ["APPEND_TO_EVENT"]
This needs to be `LOGPREP_APPEND_MEASUREMENT_TO_EVENT`

2023-11-17 07:30 UTC, dtrai2 commented
> I marked two places where the environment variable was not replaced with the new name. Other than that it works great and I will approve it as soon as this is changed.

ah thanks for that find! It was actually also a broken test. With that wrong environment variable the test should have failed. I fixed the env and added an assertion.

2023-11-17 07:51 UTC, ppcad approved these changes
Thank you!

2023-11-17 09:39 UTC, merged