Improve rule loading times in rule tree
fkie-cad/Logprep pull request #464
Opened 2023-10-27 05:32 UTC by ppcad

* Fix cnf to dnf conversion and improve its performance
* Optimize rule tree sorter performance
* Add timeout for loading rules in the rule tree
* Add rule tree changes to readme and changelog
* Fix bug in rule parsing

2023-11-03 11:05 UTC, ekneg54 commented
as we reimplement metrics now,  I suggest to wait with this to get vision about what is actual slow on loading rules and wich rules.

Am I right, that improve rule loading times is only done because restarting pipelines seems to be slow?
There are multiple things that could getting slow. Loading lists? loading rules? And so there are different ways to deal with them.  But before dealing with them we should get vision.

We implement some additional metrics for restarting pipelines. Having that, you should be able to identify what is actual slow in your configuration.

A timeout feels like a workaround and does not solves the actual problem with the risk that some rules will be missing in processing.

2023-11-03 11:24 UTC, ppcad commented
> as we reimplement metrics now, I suggest to wait with this to get vision about what is actual slow on loading rules and wich rules.
> 
> Am I right, that improve rule loading times is only done because restarting pipelines seems to be slow? There are multiple things that could getting slow. Loading lists? loading rules? And so there are different ways to deal with them. But before dealing with them we should get vision.
> 
> We implement some additional metrics for restarting pipelines. Having that, you should be able to identify what is actual slow in your configuration.
> 
> A timeout feels like a workaround and does not solves the actual problem with the risk that some rules will be missing in processing.

This change does include an optimization of rule sorting and dnf conversion. The algorithms did some redundant looping.
The dnf conversion can still explode in load time, even if the implementation would be perfectly optimized.
The conversion has simply such a high complexity.
So the timeout is needed to filter out those cases.

2023-11-17 10:38 UTC, ppcad commented
I removed the timeout.
Please have a look @ekneg54.

2023-11-21 15:58 UTC, ekneg54 requested changes
minor change in Changelog please

2023-11-21 15:58 UTC, ekneg54 commented on CHANGELOG.md
> +* improve loading times for the rule tree by optimizing the rule segmentation and sorting
version 8.0.0 is already released. please push your impovement up to the next section

2023-11-21 15:58 UTC, ekneg54 commented on CHANGELOG.md
> +* Fix the rule tree parsing some rules incorrectly, potentially resulting in more matches.
version 8.0.0 is already released. please push your impovement up to the next section

2023-11-23 09:32 UTC, ekneg54 approved these changes

2023-11-23 09:36 UTC, merged