pyproject.toml dependency and build managment
fkie-cad/Logprep pull request #526
Opened 2024-02-11 17:49 UTC by ekneg54

2024-02-13 08:02 UTC, dtrai2 requested changes
Looks quite good already. Guess we just have to try it out and see how well it will works. I just found some more mentions of the `requirements.txt` or `requirements_dev.txt` though. Just do a project wide search for those names and you should find them too. Some are for example in the files:
- `doc/source/getting_started.rst`
- `.devcontainer/Dockerfile` (as an optional comment though)
- `.github/workflows/ci.yml`
- `.github/workflows/main.yml`
- `.readthedocs.yaml`
- `README.md`
- ...

2024-02-27 15:49 UTC, ekneg54 commented
@ppcad @dtrai2 
please have a look again. the pipeline is still failing for black. But I recommend to add the additional 74 format dependent fixes after review :-D

2024-03-06 11:55 UTC, dtrai2 requested changes
I just found one small line that you can still also remove. Could you also add an entry in the changelog? The question is are we considereing this as a breaking change? The software itself didn't change, but the install procedure of logprep did, and if someone depends on the `requirements.txt` they have a problem now.

2024-03-06 11:55 UTC, dtrai2 commented on pyproject.toml
> +# version = "0.1.0"
```suggestion
```

2024-03-06 12:25 UTC, dtrai2 approved these changes

2024-03-06 13:30 UTC, merged