use aes in gcm mode for pseudonymization
fkie-cad/Logprep pull request #600
Opened 2024-06-06 13:48 UTC by ekneg54

* use AES in GCM mode to decouple key length of depseudo and analyst keys

TODO:

- [ ] add first test
- [ ] add implementation for pseudonymization
- [ ] add implementation for depseudonymization
- [ ] increase documentation
- [ ] update changelog

2024-06-10 09:38 UTC, dtrai2 commented on logprep/util/pseudo/encrypter.py
> +        public key of the depseudonymizer personel. This decouples the analyst
```suggestion
        public key of the depseudonymizer personnel. This decouples the analyst
```

2024-06-10 09:40 UTC, dtrai2 commented on logprep/util/pseudo/encrypter.py
> +        # encrpyt session key with AES depseudo key
```suggestion
        # encrypt session key with AES depseudo key
```

2024-06-10 09:41 UTC, dtrai2 commented on logprep/util/pseudo/encrypter.py
> +        cipher_aes = AES.new(session_key, AES.MODE_CTR)  # nosemgrep
```suggestion
        cipher_aes = AES.new(session_key, AES.MODE_CTR)
```

2024-06-10 09:47 UTC, dtrai2 commented on tests/unit/util/pseudo/test_decrpyter.py
> +        # decrypt encrypted encrypted session key with analyst private key
```suggestion
        # decrypt encrypted session key with analyst private key
```

2024-06-10 12:19 UTC, ekneg54 commented on logprep/util/pseudo/decrypter.py
> +        return self.pseudonymized_string[416:]
done

2024-06-10 13:35 UTC, dtrai2 approved these changes

2024-06-12 06:47 UTC, ekneg54 commented on logprep/util/pseudo/decrypter.py
> +        bytes
done

2024-06-12 06:48 UTC, ekneg54 commented on logprep/util/pseudo/encrypter.py
> +        session_key: bytes = get_random_bytes(16)
now its in the `logprep.util.defaults` module as constant

2024-06-12 12:18 UTC, dtrai2 requested changes

2024-06-12 12:18 UTC, dtrai2 commented on logprep/util/pseudo/encrypter.py
> +        )
how about you implement this as `__str__` or `__repr__` method inside the `GCMPseudonym` dataclass?

2024-06-12 12:18 UTC, dtrai2 commented on logprep/util/pseudo/encrypter.py
> +        )
same as above

2024-06-12 13:04 UTC, dtrai2 approved these changes

2024-06-12 13:19 UTC, merged