fix http input bug
fkie-cad/Logprep pull request #657
Opened 2024-08-27 12:36 UTC by djkhl

2024-08-27 15:03 UTC, ekneg54 requested changes

2024-08-27 15:03 UTC, ekneg54 commented on logprep/framework/pipeline.py
> +            return PipelineResult(results=[], event=event, pipeline=[], event_received=event)
```suggestion
```

instead  consider initialize result with None after line 259

2024-08-27 15:03 UTC, ekneg54 commented on logprep/framework/pipeline.py
> +            return PipelineResult(results=[], event=event, pipeline=[], event_received=event)
and we should tests this. it was not a good idea, to implement this without tests. sorry... shame on me.

2024-08-29 15:35 UTC, ekneg54 requested changes

2024-08-29 15:58 UTC, djkhl commented on tests/unit/framework/test_pipeline.py
> +        assert isinstance(result, type(None))
yes looks a lot better

2024-08-29 16:20 UTC, ekneg54 approved these changes

2024-08-29 16:20 UTC, merged