add replacer processor
fkie-cad/Logprep pull request #672
Opened 2024-09-21 15:09 UTC by ekneg54

2025-04-03 13:00 UTC, ppcad commented
@ekneg54 Could you please also have a look? I could not add you as reviewer, because you created this pull request.

2025-04-07 07:02 UTC, kmeinerz requested changes
Please take a look at my suggestions. I mainly added some type annotations, but also there are some cases, which are not covered by tests, e.g. ```template``` is ```None```.

2025-04-08 11:00 UTC, kmeinerz approved these changes
I suggest adding ```# pylint: disable=protected-access``` to test_replacer.py to handle the warning when accessing _handle_wildcard in the tests.

Everything else looks great to me—I'm happy to give my approval!

2025-04-08 11:00 UTC, kmeinerz commented on tests/unit/processor/replacer/test_replacer.py
> +# pylint: disable=missing-docstring
```suggestion
# pylint: disable=missing-docstring
# pylint: disable=protected-access
```

2025-04-08 12:16 UTC, merged