Reduce to one rule tree
fkie-cad/Logprep pull request #731
Opened 2024-12-17 11:02 UTC by ppcad

2024-12-18 14:48 UTC, dtrai2 requested changes
Ah thanks for the diligent work! Quite a feat. It'll take out unnecessary the complexity.

I only found some tiny things you can still remove. Also in the following two files I found references to `generic` and `specific` rules:

- `rule.py` line 20 & 21
- `test_full_configuration.py` line 237 and 242

2024-12-18 14:48 UTC, dtrai2 commented on tests/unit/processor/dropper/test_dropper.py
> +        return self.CONFIG["rules"]
I think you can delete this, it's already defined in the parent class.
```suggestion
```

2024-12-18 14:48 UTC, dtrai2 commented on tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py
> +        return self.CONFIG.get("rules")
I think you can delete this, it's already defined in the parent class.
```suggestion
```

2024-12-18 14:48 UTC, dtrai2 commented on tests/unit/processor/datetime_extractor/test_datetime_extractor.py
> +        return self.CONFIG.get("rules")
I think you can delete this, it's already defined in the parent class.
```suggestion
```

2024-12-18 14:48 UTC, dtrai2 commented on tests/unit/processor/concatenator/test_concatenator.py
> +        return self.CONFIG["rules"]
I think you can delete this, it's already defined in the parent class.
```suggestion
```

2024-12-18 14:48 UTC, dtrai2 commented on tests/unit/processor/generic_adder/test_generic_adder.py
> +        return self.CONFIG.get("rules")
I think you can delete this, it's already defined in the parent class.
```suggestion
```

2024-12-18 14:48 UTC, dtrai2 commented on tests/unit/processor/generic_resolver/test_generic_resolver.py
> +        return self.CONFIG["rules"]
I think you can delete this, it's already defined in the parent class.
```suggestion
```

2024-12-18 14:48 UTC, dtrai2 commented on tests/unit/processor/geoip_enricher/test_geoip_enricher.py
> +        return self.CONFIG["rules"]
I think you can delete this, it's already defined in the parent class.
```suggestion
```

2024-12-18 14:48 UTC, dtrai2 commented on tests/unit/processor/labeler/test_labeler.py
> +        return self.CONFIG["rules"]
I think you can delete this, it's already defined in the parent class.
```suggestion
```

2024-12-18 14:48 UTC, dtrai2 commented on tests/unit/processor/template_replacer/test_template_replacer.py
> +        return self.CONFIG.get("rules")
I think you can delete this, it's already defined in the parent class.
```suggestion
```

2024-12-19 07:05 UTC, ppcad commented
> Ah thanks for the diligent work! Quite a feat. It'll take out unnecessary the complexity.
> 
> I only found some tiny things you can still remove. Also in the following two files I found references to `generic` and `specific` rules:
> 
> * `rule.py` line 20 & 21
> * `test_full_configuration.py` line 237 and 242

Thank you for the review, I've changed it.

2024-12-19 08:36 UTC, dtrai2 approved these changes

2024-12-20 11:55 UTC, merged