Fix 73 consistency for applying rules
fkie-cad/Logprep pull request #74
Opened 2022-04-21 12:01 UTC by ekneg54

Implements strategy pattern to processors to ensure that all processors have a consistent behavior for the order of applying generic and specific rules.

Thanks to the strategy pattern this behavior is easy changeable on a general or processor level.

2022-04-27 05:58 UTC, ppcad commented
There are some unused imports in generic adder (time, TimeMeasurement) and domain resolver (datetime).

2022-04-27 07:16 UTC, ekneg54 commented
removed unused imports

2022-04-27 10:16 UTC, urdit52 requested changes

2022-04-27 10:23 UTC, dtrai2 approved these changes

2022-04-27 10:24 UTC, urdit52 approved these changes

2022-04-28 13:24 UTC, ppcad requested changes

2022-04-28 13:30 UTC, ppcad approved these changes

2022-04-28 16:23 UTC, merged