Refactor selective extractor to rule based
fkie-cad/Logprep pull request #79
Opened 2022-04-27 14:11 UTC by ekneg54

2022-05-03 16:59 UTC, ekneg54 commented
reopen to trigger pipeline

2022-05-04 09:58 UTC, dtrai2 requested changes

2022-05-04 11:25 UTC, dtrai2 approved these changes

2022-05-05 06:19 UTC, dtrai2 requested changes

2022-05-05 06:19 UTC, dtrai2 commented on doc/source/user_manual/rule_language.rst
> +It contains a dictionary of field names and values that should be extracted.
```suggestion
It contains a dictionary of field names that should be extracted and a target topic to which they should be send to.
```

2022-05-05 06:19 UTC, dtrai2 commented on doc/source/user_manual/rule_language.rst
> +In the following example, the field :code:`extract_test.field.extract` with the value :code:`extracted value` is being extracted
Is the field in the filter automatically the root of the extraction? If not I think it should be like this:

```suggestion
In the following example, the field :code:`field.extract` with the value :code:`extracted value` is being extracted
```

2022-05-05 06:19 UTC, dtrai2 commented on doc/source/user_manual/rule_language.rst
> +    :caption: Example with extract from field list
```suggestion
    :caption: Example rule with extract from field list
```

2022-05-05 06:19 UTC, dtrai2 commented on doc/source/user_manual/rule_language.rst
> +and send to the topic :code:`topcic_to_send_to`
```suggestion
and send to the topic :code:`topcic_to_send_to`.
```

2022-05-05 06:19 UTC, dtrai2 commented on doc/source/user_manual/rule_language.rst
> +    :caption: Example with extract from file
```suggestion
    :caption: Example rule with extract from file
```

2022-05-05 06:19 UTC, dtrai2 commented on doc/source/user_manual/rule_language.rst
> +    :caption: Example with extract from file
```suggestion
    :caption: Example rule with extract from file
```

2022-05-05 08:03 UTC, dtrai2 approved these changes

2022-05-05 11:10 UTC, merged