Fix auto tester without rules
fkie-cad/Logprep pull request #85
Opened 2022-05-02 10:09 UTC by ppcad

Fix auto tester without rules

2022-05-03 17:10 UTC, ekneg54 requested changes
This file has zero test coverage.
In my opinion we should add some tests to ensure, that this does not happen again.

2022-05-09 13:50 UTC, ppcad commented
I added basic tests for the test coverage in the auto tester, since this was what caused the crash.
I would like to add further tests to cover other parts of the auto tester in another branch.

2022-05-11 06:08 UTC, ppcad commented
Added some more tests and resolved merge conflicts.

2022-05-13 18:18 UTC, ekneg54 approved these changes

2022-05-13 18:18 UTC, merged