Refactor Prometheus Metrics
fkie-cad/Logprep pull request #91
Opened 2022-05-10 12:42 UTC by dtrai2

To improve the visualizations in grafana a few changes have been
made. First and foremost stale metric database files will be removed
now when a pipeline fails. Furthermore, the metrics are prefixed
with 'logprep_' and the label is now called 'component'.
Additionally, the status logger is not stored in a list anymore
but in a namedtuple, which makes the unwrapping easier. Last but
not least a small fix in the documentation was done, variables
renamed and some linting issues fixed.

2022-05-11 13:14 UTC, urdit52 commented on logprep/util/processor_stats.py
> +                        float(metric_value) if not math.isnan(float(metric_value)) else 0.0
please revise.

2022-05-11 13:17 UTC, urdit52 commented on logprep/util/prometheus_exporter.py
> +    multi_processing_dir = ""
```suggestion
    multi_processing_dir = None
```

2022-05-11 13:18 UTC, urdit52 commented on logprep/util/prometheus_exporter.py
> +    multi_processing_dir = ""
also, please add a type hint

2022-05-11 13:28 UTC, urdit52 commented on logprep/util/prometheus_exporter.py
> +        ]
this list comprehension might be a little hard to read.

2022-05-12 07:00 UTC, urdit52 requested changes
Added a few suggestions - please review.

2022-05-12 07:00 UTC, ekneg54 approved these changes

2022-05-13 06:37 UTC, urdit52 approved these changes
Looks good to me, thank you for incorporating the suggestions.

2022-05-13 18:20 UTC, merged